def _split(seq):
    return [seq[(i * 3) : (i * 3 + 3)] for i in range(len(seq) // 3)]


CODON_MAP = {
    "START": "ATG",
    "STOP": "TAATGATAG",
    "REST": "GCTGCCGCAGCGCGTCGCCGACGGAGAAGGAATAACGATGACTGTTGCCAACAG"
    "GAAGAGGGTGGCGGAGGGCATCACATTATCATATTATTGCTTCTCCTACTGAAAAAGTTTTTC"
    "CCTCCCCCACCGTCTTCCTCATCGAGTAGCACTACCACAACGTGGTATTACGTTGTCGTAGTG",
}

for key in CODON_MAP.keys():
    CODON_MAP[key] = _split(CODON_MAP[key])
